### ISSUE TITLE
Installation guide request

### ISSUE THREAD

**Issue by QiuHong-1202** [arturs-berzins/boundary_sensitivity#1]
Thanks for your great work!

I've noticed that the repository currently lacks an installation guide for the project. I've attempted to use various versions of pytorch and dgl, but unfortunately, I haven't been successful. Could you please provide details about the required environment for your project? Thank you in advance!

**Comment by arturs-berzins** [comment]
Hi QioHong, thanks for raising the issue. `dgl` was not strictly necessary, so I removed it and some other unnecessary code. I also added a `requirements.txt`. Let me know if an issue persists.

**Comment by QiuHong-1202** [comment]
The problem was fixed, thank you very much!
